# fly.toml file generated for infisical-production on 2023-04-08T01:30:53+08:00

app = "infisical-production"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"
[processes]
  web = "/usr/sbin/nginx -c /etc/nginx/nginx.conf"
  pm2 = "pm2-runtime /app/ecosystem.config.js"

[env]

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 8080
  force_https = true
  [http_service.concurrency]
    type = "requests"
    soft_limit = 1000
    hard_limit = 5000