name: Deploy to Fly.io

on:
  workflow_run:
    workflows: [Publish Container]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.0.509
      - run: flyctl deploy --image=ghcr.io/${{ github.repository }}:${{  github.ref_name }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_ACCESS_TOKEN }}
      
